version: '3.3'
services:
  db:
    image: mysql-docker1
    restart: always
    environment:
         MYSQL_ROOT_PASSWORD: pucsd

  db1:
    image: mysql-docker2
    restart: always
    environment:
         MYSQL_ROOT_PASSWORD: pucsd

  db3:
    image: mysql-docker3
    restart: always
    environment:
         MYSQL_ROOT_PASSWORD: pucsd

